# -*- coding: utf-8 -*-
"""ITDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VgR_1FiT_V_-cVPM6y6eHk-cjEnIo0e3
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile TourismPrediction.py

! wget -q -O - ipv4.icanhazip.com

! streamlit run TourismPrediction.py & npx localtunnel --port 8501