# -*- coding: utf-8 -*-
"""ITDS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCVbmvOWXJ36OjhRQdpS5Bg_3PWwo4MR
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile TourismPrediction.py

! wget -q -O - ipv4.icanhazip.com

! streamlit run TourismPrediction.py & npx localtunnel --port 8501
